version: '3.3'
services:
  php-apache-environment:
    container_name: php-apache
    image: php:7.0-apache
    volumes:
      - ./src:/var/www/html/
    build: 
        context: './src/'
        dockerfile: dockerfile 
    ports:
      - 8000:80
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
        MYSQL_DATABASE: MY_DATABASE
        MYSQL_USER: php
        MYSQL_PASSWORD: php
    ports:
        - "3306:3306"

  phpMyAdmin:
      image: phpmyadmin/phpmyadmin
      container_name: codeigniter-phpmyadmin
      ports:
        - "8188:80"
      environment:
          PMA_HOST: db